"use client";

import { useState } from "react";
import ShareButton from "./ShareButton";

interface ReportOutputProps {
  report: string;
  template?: string;
  plan?: string;
}

export default function ReportOutput({ report, template = "daily", plan = "free" }: ReportOutputProps) {
  const [copied, setCopied] = useState(false);

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(report);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      const textarea = document.createElement("textarea");
      textarea.value = report;
      document.body.appendChild(textarea);
      textarea.select();
      document.execCommand("copy");
      document.body.removeChild(textarea);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };

  const handleDownloadTxt = () => {
    const blob = new Blob([report], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `nippo_${new Date().toISOString().slice(0, 10)}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handleDownloadPdf = async () => {
    const { default: jsPDF } = await import("jspdf");

    const doc = new jsPDF({
      orientation: "portrait",
      unit: "mm",
      format: "a4",
    });

    const templateLabel =
      template === "daily" ? "日報" : template === "weekly" ? "週報" : "クライアント報告書";
    const today = new Date().toLocaleDateString("ja-JP", {
      year: "numeric",
      month: "long",
      day: "numeric",
    });

    // フォント設定（日本語対応のため Unicode をサポート）
    doc.setFont("helvetica");

    // ヘッダー
    doc.setFillColor(37, 99, 235);
    doc.rect(0, 0, 210, 28, "F");
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(18);
    doc.text("NippoGen - " + templateLabel, 14, 18);

    // 日付
    doc.setTextColor(100, 100, 100);
    doc.setFontSize(10);
    doc.text(today, 14, 36);

    // 区切り線
    doc.setDrawColor(200, 200, 200);
    doc.line(14, 40, 196, 40);

    // 本文
    doc.setTextColor(30, 30, 30);
    doc.setFontSize(11);

    const lines = doc.splitTextToSize(report, 175);
    let y = 48;
    const pageHeight = 280;

    for (let i = 0; i < lines.length; i++) {
      if (y > pageHeight) {
        doc.addPage();
        y = 20;
      }
      doc.text(lines[i], 14, y);
      y += 6;
    }

    // フッター
    const pageCount = doc.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      doc.setFontSize(8);
      doc.setTextColor(150, 150, 150);
      doc.text("Generated by NippoGen - https://nippogen-app.vercel.app", 14, 290);
      doc.text(`${i} / ${pageCount}`, 190, 290);
    }

    doc.save(`nippo_${new Date().toISOString().slice(0, 10)}.pdf`);
  };

  if (!report) return null;

  return (
    <div className="bg-white rounded-2xl shadow-sm border border-gray-200 p-6 sm:p-8 animate-fade-in">
      <div className="flex items-center justify-between mb-4">
        <h2 className="text-lg font-bold text-gray-900">生成された日報</h2>
        <div className="flex gap-2">
          <button
            onClick={handleCopy}
            className="text-xs font-medium px-3 py-1.5 rounded-lg border border-gray-300 hover:bg-gray-50 transition-colors"
          >
            {copied ? "コピー済み!" : "コピー"}
          </button>
          <button
            onClick={handleDownloadTxt}
            className="text-xs font-medium px-3 py-1.5 rounded-lg border border-gray-300 hover:bg-gray-50 transition-colors"
          >
            .txt保存
          </button>
          {plan === "pro" ? (
            <button
              onClick={handleDownloadPdf}
              className="text-xs font-medium px-3 py-1.5 rounded-lg border border-blue-300 bg-blue-50 text-blue-700 hover:bg-blue-100 transition-colors"
            >
              PDF保存
            </button>
          ) : (
            <span className="text-xs font-medium px-3 py-1.5 rounded-lg border border-gray-200 bg-gray-50 text-gray-400 cursor-not-allowed" title="Pro プラン限定">
              PDF保存 🔒
            </span>
          )}
        </div>
      </div>
      <div className="bg-gray-50 rounded-xl p-5 text-sm leading-relaxed text-gray-800 whitespace-pre-wrap border border-gray-100">
        {report}
      </div>

      {/* SNS共有ボタン */}
      <div className="mt-6 pt-5 border-t border-gray-100">
        <p className="text-xs text-gray-500 mb-3">この日報を共有する</p>
        <ShareButton report={report} template={template} />
      </div>
    </div>
  );
}
